env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: false
    globalReturn: true
  ecmaVersion: 2020
  sourceType: module
rules:
  camelcase: 0
  'arrow-body-style': 0
  'react/no-multi-comp': 0
  'no-multi-spaces': 0
  'global-require': 0
  'consistent-return': 0
  'no-console': 0
  'no-trailing-spaces': 0
  no-restricted-syntax: 0
